spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka


spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=vehicle-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://VEHICLE-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/vehicles/**

spring.cloud.gateway.server.webmvc.routes[2].id=booking-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/bookings/**

eureka.instance.prefer-ip-address=true


jwt.secret=TXlTdXBlclNlY3VyZUpXVFNlY3JldEtleUZvckhTMjU2QWxnb3JpdGhtMTIzNDU2Nzg5


logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.server.mvc=DEBUG
