spring.application.name=user-service

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/userdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true

jwt.secret=@P1u2n3e4e5e6t7a8g9n0h1o2t3r4i5
jwt.expiration=86400000